#!/usr/bin/env groovy

/**
 * Jenkinsfile for Sample Python Library
 * 
 * This demonstrates how to use the Python Library Shared Library
 */

@Library('python-library-shared-lib') _

// Minimal configuration - everything else is auto-detected
def pipelineConfig = [
    // Note: The following are automatically detected from repository name:
    // - sonarProjectKey: 'sample-python-lib'
    // - nexusIqApplicationId: 'sample-python-lib'
    // - artifactoryRepo: 'sample-python-lib'
    
    // Infrastructure URLs are loaded from shared library config
    // - sonarHostUrl: from common-config.yml
    // - nexusIqUrl: from common-config.yml
    // - artifactoryUrl: from common-config.yml
]

// Run the pipeline
pythonCIPipeline(pipelineConfig) 